<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "kd_calendar"
 *
 * Auto generated by Extension Builder 2016-02-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Calendar',
	'description' => 'Extension to handle calendar events. Can handle google calendar by google api.',
	'category' => 'plugin',
	'author' => 'Kevin Ditscheid',
	'author_email' => 'kevinditscheid@gmail.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);